# .travis.yml
# Configure Travis CI service to build Sentilo platform, http://github.com/sentilo/sentilo
#
language: java

jdk:
  - oraclejdk7
  - openjdk6
  
after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura
